### ISSUE TITLE
Preload links broken, if there is a parent path

### ISSUE THREAD

**Issue by vralle** [webdiscus/html-bundler-webpack-plugin#141]
## Current behaviour
We import the font file in the style file:
```scss
@font-face {
  font-family: Logo;
  font-style: normal;
  font-weight: 400;
  src: url("@src/font/subset/font.woff2") format("woff2"), url("@src/font/subset/font.ttf") format("ttf");
  font-display: swap;
}
```

Webpack cfg has font loader:
```js
module: {
  rules: [
    {
      test: /\.(ttf|woff|woff2)(\?.*)?$/i,
      type: "asset",
      parser: {
        dataUrlCondition(source) {
          return Buffer.byteLength(source) <= 2 * 1024; // maxSize: 2 * 1024 bytes
        },
      },
  ],
}
```

The plugin has preload options:
```js
preload: [
  {
    test: /\.m?js$/i, // using a link to src
    as: "script",
  },
  {
    test: /\.woff2$/,
    attributes: { as: "font", crossorigin: true },
  },
],
```

This configuration did not create any problems as long as the Webpack [public path](https://webpack.js.org/configuration/output/#outputpublicpath) was empty:
```js
output: {
  path: path.resolve(__dirname, 'dist'),
  publicPath: "",
  filename: join("static", "js", "[name].[contenthash].js"),
  chunkFilename: join("static", "js", "[id].[contenthash].js"),
  cssFilename: join("static", "css", "[name].[contenthash].css"),
}
```

But if we want to set the value of public path, after compilation we're getting trouble

Step 1 - `publicPath: "/"` (links with absolute path starting at root)

The compiled output fragments:

`app.css`
```css
@font-face {
  font-family: Logo;
  font-style: normal;
  font-weight: 400;
  src: url(/static/font/subset/font.woff2)format("woff2"), url(/static/font/subset/font.ttf)format("ttf");
  font-display: swap
}
```

`index.html`
```html
<head>
<link href="/static/js/app.41fa4ae00.js" rel="preload" as="script">
<link href="/static/css/static/font/subset/font.woff2" rel="preload" type="font/woff2" as="font" crossorigin>
<link href="/static/css/app.f302515e3.css" rel="style">
```

All the links here are absolute, but the font preload link has a problem. It has path to css file (`/static/css/`), where is the link to font, and plus a link to font (`static/font/subset/font.woff2`).

Step 2 - `publicPath: "https://example.site"` (URL without trailing slash)

Output:

`app.css`
```css
@font-face {
  font-family: Logo;
  font-style: normal;
  font-weight: 400;
  src: url(https://example.site/static/font/subset/font.woff2)format("woff2"), url(https://example.site/static/font/subset/font.ttf)format("ttf");
  font-display: swap
}
```

The same compiled fragment of `index.html`:
```html
<link href="https://example.site/static/js/app.2a5a42641.js" rel="preload" as="script">
<link href="https://example.site/static/css/https:/example.site/static/font/subset/font.woff2" rel="preload" type="font/woff2" as="font" crossorigin>
<link href="https://example.site/static/css/app.f302515e3.css" rel="stylesheet">
```
Now all the links here are fine except the font preload link.

Step 3 - `publicPath: "https://example.site/"`  (URL with trailing slash)

Output:

`app.css`
```css
@font-face {
  font-family: Logo;
  font-style: normal;
  font-weight: 400;
  src: url(https://example.site/static/font/subset/font.woff2)format("woff2"), url(https://example.site/static/font/subset/font.ttf)format("ttf");
  font-display: swap
}
```

`index.html`
```html
<link href="https://example.site/static/js/app.29261e067.js" rel="preload" as="script">
<link href="https://example.site/static/css/https:/example.site/static/font/subset/font.woff2" rel="preload" type="font/woff2" as="font" crossorigin>
<link href="https://example.site/static/css/app.f302515e3.css" rel="stylesheet">
```
Same problem with font preload link.

- [ ] repository URL
- [x] example code

## Environment

- OS: Debian
- version of Node.js: v22.12.0
- version of Webpack: 5.97.1
- version of the Plugin:

## Additional context
Obviously, preload links broken, if there is a parent path.

Also, the dynamic script loading links are ignored an absolute path for `publicPath` and still always relative, but I think that's Webpack's side. And those relative links are broken if entry points are placed in subdirectories (relative to [issue 140](https://github.com/webdiscus/html-bundler-webpack-plugin/issues/140))

## Appreciation for the useful project

- [x] After the problem is resolved, do not forget to give a star ⭐
