### ISSUE TITLE
The plugin changes DOM when importing SVG files into HTML

### ISSUE THREAD

**Issue by vralle** [webdiscus/html-bundler-webpack-plugin#154]
## Current behavior

When an SVG file is imported into HTML, the parent IMG HTML element is replaced by the SVG tag.

Source HTML:
```html
<img src="@images/icons/iphone.svg">
```

Output:
```html
<svg viewBox="0 0 24 24" with="24" height="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M15.5 1h-8C6.12 1 5 2.12 5 3.5v17C5 21.88 6.12 23 7.5 23h8c1.38 0 2.5-1.12 2.5-2.5v-17C18 2.12 16.88 1 15.5 1zm-4 21c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm4.5-4H7V4h9v14z"/></svg>
```

Different behavior for importing fonts, binary images, and SVGs: [inline-all-asset-to-html](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/v4.17.0/test/cases/inline-all-asset-to-html)

This behavior disrupts the file import logic and [conflicts with data URI encoding](https://github.com/webdiscus/html-bundler-webpack-plugin/issues/153). Additionally, it can lead to style/JS collisions if IMG/SVG selectors are used.

## Expected behavior

Manipulating the DOM can lead to unpredictable behavior. The plugin should avoid manipulating the DOM to prevent any unpredictable consequences. It is necessary to restore the standard behavior of Webpack's file import to regain the ability to encode SVGs in data URIs.

SVG import as an HTML element can be implemented in the following ways:
- An arbitrary template engine function that uses specialized libraries such as [Iconify Utils](https://iconify.design/docs/libraries/utils/) and [Iconify Tools](https://iconify.design/docs/libraries/tools/). You can see how it works for JS with [unplugin-icons](https://github.com/unplugin/unplugin-icons);
- The plugin may offer an SVG import feature that replaces the parent IMG tag, but only if a specific query parameter is used. The well-known `raw` parameter is similar in meaning. However, replacing the IMG tag with an SVG goes beyond the typical behavior expected from the `raw` parameter, which could lead to new issues. It is necessary to define a unique name for the query parameter that accurately reflects its semantics and does not conflict with known Webpack query parameters. Perhaps the plugin should move away from using `RuleSetRule.parser.dataUrlCondition`, thereby giving users the unique ability to embed any SVG using a query parameter.

I will try to add more information in the next few days.

## Environment

- version of Webpack: 5.98.0
- version of the Plugin: 4.18.0

## Appreciation for the useful project

- [x] After the problem is resolved, do not forget to give a star ⭐

**Comment by vralle** [comment]
I have updated the text, but there might be additional ideas or objections.

**Comment by webdiscus** [comment]
Hello @vralle,

thank you for the reporting. I agree with your propose.

In next version I will change the inlining behaviour:

1. defaults, inline SVG as dataURL of `img.src`, not replace `<img>` tag with `<svg>`
   Optional, SVG can be inlined into DOM as `svg` tag:
   - (for single image) - if used specific query param (not `raw`), e.g.  `?embed` (as proposal only, we can discuss about it)
   - (for all images) - if specified in new plugin `svg` option, e.g.:
      ```js
      svg: {
        inline: 'dataUrl' | 'embed' | true | false | 
      }
      ```
      where:
        - `'dataUrl'` - defaults, inline SVG as dataUrl in img.src
        - `embed` - replace `img` tag witch  `svg` tag (excluding other tags, e.g. `link` for favicon)
        - true - force (regardless webpack rules) inline SVG as default `'dataUrl'`
        - false - force disable inline SVG (stay as is)

2. defaults, encode SVG in dataUrl using `encodeURIComponent()`, which encodes all reserved chars, including `<>` and spaces.

What do you think about?

**Comment by vralle** [comment]
Hi @webdiscus!

From the [discussion](https://github.com/webdiscus/html-bundler-webpack-plugin/discussions/152) I got that importing SVG into HTML affects imports into other modules such as CSS (JS?). I would like your opinion on how the planned changes will help isolate the SVG import into HTML from the import into other modules?

**Comment by vralle** [comment]
> 2. defaults, encode SVG in dataUrl using encodeURIComponent(), which encodes all reserved chars, including <> and spaces.

I didn't quite understand this, because the default encoding is base64 and maybe someone needs it.

**Comment by webdiscus** [comment]
> I didn't quite understand this, because the default encoding is base64 and maybe someone needs it.

not always SVG is base64, for example, using `'mini-svg-data-uri` in `generator.dataUrl()` returns semi-encoded (spaces are not encoded as %20) SVG as plain text.

**Comment by webdiscus** [comment]
SVG as base64 makes no sense, since it is large and unreadable. For some reason it may be as base64, we can use any option for that.

**Comment by vralle** [comment]
> not always SVG is base64, for example, using 'mini-svg-data-uri in generator.dataUrl() returns semi-encoded (spaces are not encoded as %20) SVG as plain text.

I would prefer to act by default as intended in Webpack. If necessary, a developer can change a coding algorithm. Otherwise, we make the decision for the developers by changing the default actions and calling the new actions default actions. 

In any case, if the developer has a working `RuleSetRule.generator.dataUrl()`, then it is not a critical issue.

**Comment by vralle** [comment]
> (for all images) - if specified new plugin svg option (like js, css), e.g.:
> ```js
svg: {
  inline: 'dataUrl' | 'embed' | true | false 
  encode: 'xml' (default) | 'base64'  // only for inline as dataUrl
}
```

The encoding option duplicates the webpack options. I'm not sure about the need to override the webpack settings that webpack 5 is proud of.

And what if a developer wants to choose his own algorithm?

**Comment by webdiscus** [comment]
> The encoding option duplicates the webpack options. I'm not sure about the need to override the webpack settings that webpack 5 is proud of.

I will keep all relevant options at one place. Using `module.rules.generator....` is uncomfortable.

> And what if a developer wants to choose his own algorithm?

Yes of cause. I, as developer prefer to inline dataUrl as `svg+xml`.

**Comment by webdiscus** [comment]
## Base64 Encoding

Example:
```html
<img src="data:image/svg+xml;base64,PHN2ZyB4bWxu..."/>
```

✅ **Pros:**
- Works reliably in all browsers, no issues with special characters.
- Avoids potential problems with misinterpreted characters in some contexts (e.g., CSS `background-image`).

❌ **Cons:**
- Larger size (~33% increase due to base64 overhead).
- Less readable – encoded data is not human-readable.
- Extra processing – requires encoding/decoding.

## URL-Encoded `svg+xml`

Example:
```html
<img src="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg'.../>"/>
```
Or, URL-encoded:
```html
<img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20...%2F%3E"/>
```

✅ **Pros:**

- Smaller size (compared to base64, as no extra encoding overhead).
- More readable – can be inspected and edited directly.
- Better compression when used in inline CSS/HTML (if the document is gzipped).
- Direct browser rendering without decoding overhead.

❌ **Cons:**

- Special characters need escaping (#, %, <, >).
- Some contexts require encoding (e.g., CSS background-image).
- Potential browser inconsistencies if not properly escaped.

**Comment by webdiscus** [comment]
@vralle 

I know, what Webpack defaults uses base64 encoding, even for SVG:
```
data:image/svg+xml;base64,PHN2ZyB4b...
```

but I don't agree with that, because escaped raw SVG in dataURL is smaller and more efficient. The `base64` encoding increases SVG size by about 33%.

I understand, Webpack standard should be preferred, but not must, since the Plugin is to make DX better. We can documented, that plugin behaviours is different from Webpack defaults. Of course the encoding can be configured via plugin options or in `module.generatorOptions.dataUrl.encoding`.

I'm agree to escape all chars in  the SVG in dataURL:
```
data:image/svg+xml,%3Csvg%20xmlns%3D%22
```

What do you think?

**Comment by vralle** [comment]
Hi @webdiscus!

> the encoding can be configured via plugin options or in module.generatorOptions.dataUrl.encoding

That's enough for me.

I think it's important to support abstractions, leaving the choice to users.
_Analysis required_:
At the same time, the plugin support may be easier if the plugin renounces features that can be implemented by users: minification, Markdown parsing, SVG encoding, maybe something else.

**Comment by webdiscus** [comment]
New beta is released: `v4.19.0-beta.2`.

### 🔥 BREAKING CHANGES by inlining SVG only

- Inline `<img src="icon.svg">`:
  - OLD: replaces `<img>` with `<svg>` tag
  - NEW: inlines SVG as escaped data URL. Use new `svg.inline.embed = true` option to keep old behaviour.
- Encoding of data URL:
  - OLD: defaults, escaped URL (`#%` chars only), e.g. `data:image/svg+xml,<svg>...</svg>`
  - NEW: defaults, base64 encoded, e.g. `data:image/svg+xml;base64,iVBO` or full escaped URL, e.g. `data:image/svg+xml,%3Csvg%20` regards `generator.dataUrl.encoding` option.


### ✨ Feature

New `svg` plugin option:

```ts
type SvgOptions = {
  enabled?: boolean;
  // RegEx to match SVG files.
  // Defaults `/\.svg/i`.
  test?: RegExp;
  inline?: {
    // Enable inline SVG by replacing <img> with <svg>, only in HTML.
    // Equivalent to query: `?inline=embed` | `?embed`.
    // Defaults `false`.
    embed?: boolean;
    // Data URL encoding, overrides `generator.dataUrl.encoding` option.
    // Equivalent to query: `?inline=base64` | `?inline=escape`.
    // Defaults the `generator.dataUrl.encoding` option, if undefined then `base64`.
    encoding?: 'base64' | false;
  };
};
```

### Bugfix

Consider `generator.dataUrl()` and `generator.dataUrl.encoding` Webpack options. Fixes #153 .

**Comment by vralle** [comment]
Hello @webdiscus!

Thank you, that's great!

I've updated repo: [vralle/svg-data-uri-in-css](https://github.com/vralle/svg-data-uri-in-css)

Force to embed SVG - `viewBox` is missed, the render size is incorrect. Needs to check more SVG attributes.

The callback for `module.generator.dataUrl` works for all scenarios without exception, although embedding or linking to an external file does not require encoding.

![Image](https://github.com/user-attachments/assets/6b86b3d9-665d-4013-ac56-7252fb9f0dd9)

Dummy import SVG with `embed` query parameter in CSS doesn't call an error, instead quietly does the default import.

**Comment by vralle** [comment]
> 1 commit
> 150 files changed

It looks like a huge job. Honestly, I didn't expect it.

**Comment by webdiscus** [comment]
@vralle 

Thank you for the feedback.
I have already fixed the first BUG with missing attributes when used `generator.dataUrl()` function.

Since new version has the breaking changes for SVG rendering, 98% of changed files are "expected" test files.

**Comment by vralle** [comment]
> Since new version has the breaking changes for SVG rendering, 98% of changed files are "expected" test files.

I've looked at the changes. It's a lot in any case.

**Comment by webdiscus** [comment]
@vralle 

The `v4.19.0-beta.3` fixes the point `1)`.

> 2) Dummy import SVG with embed query parameter in CSS doesn't throw an error, instead silently performs the default import.

I think it would be better to display a warning rather than throw an exception.

> 3) The callback for `module.generator.dataUrl` works for all scenarios without exception, although embedding or linking to an external file does not require encoding.

The `module.generator.dataUrl` will be called for every matching asset from Webpack module core. 
I can't influence this and forbid to call the function `module.generator.dataUrl()`.

**Comment by vralle** [comment]
Hello @webdiscus!

Thank you, that's great!

I've updated repo: [vralle/svg-data-uri-in-css](https://github.com/vralle/svg-data-uri-in-css)

Added examples of SVG import into JavaScript.

HTML - Ok.

CSS:

1. Webpack doesn't have any warnings for `embed`.

JS:

1. Webpack doesn't have any warnings for `embed`. Instead, SVGs are encoded. This behavior can cause an error if the imported string is used as a DOM element.
2. SVGs imported with the "inline" parameter are encoded in Base64
3. Import SVGs with `raw` parameter as `asset/source` are OK (see Webpack config for SVG).

> I think it would be better to display a warning rather than throw an exception.

I agree

**Comment by webdiscus** [comment]
@vralle 

thank you for the feedback.

The warning (if ?embed query used in CSS or JS) will be implemented in the next beta version. I'm already doing this.

There is an example of the warning:

![Image](https://github.com/user-attachments/assets/0932f360-ff8e-4904-9ceb-4fc738a1efff)

Since the same SVG file can be used in HTML, CSS, or JS, it's important to display the source (issuer) file of the SVG file.

Do you have any suggestion for the warning message?

**Comment by vralle** [comment]
> if ?embed query used in CSS or JS

Yes

> There is an example of the warning
> Do you have any suggestion for the warning message?

I'm a little confused by the possibility of another module/loader/plugin using a query parameter. There are no ideas at the moment.

**Comment by vralle** [comment]
> The v4.19.0-beta.3

Additionally:

`module.generator.dataUrl` is ignored for CSS/JS.  SVG are encoding in Base64.

**Comment by webdiscus** [comment]
See please the tests (webpack config and expected folder):

- [svg-inline-generator-dataUrl-encoding-base64](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/beta/test/cases/svg-inline-generator-dataUrl-encoding-base64)
- [svg-inline-generator-dataUrl-encoding-false](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/beta/test/cases/svg-inline-generator-dataUrl-encoding-false)
- [svg-inline-generator-dataUrl-fn-query-js](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/beta/test/cases/svg-inline-generator-dataUrl-fn-query-js)
- [svg-inline-generator-dataUrl-fn](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/beta/test/cases/svg-inline-generator-dataUrl-fn)

What is wrong?

**Comment by vralle** [comment]
I see that the tests are correct. But if you use my repository above, the SVGs are imported with Base64 encoding.
In the local copy, I removed `oneOf` and `asset/source` options, but it did not help.

**Comment by vralle** [comment]
Stop. It was bug with `Live preview` for vscode. The output is correct. Sorry,

**Comment by vralle** [comment]
Result from my repo:


src:
```css
.i-bg-whatsapp::before {
  background-image: url("@src/img/icons/whatsapp.svg?from-css");
}```

output:
```css
.i-bg-whatsapp::before {
  background-image: url("@src/img/icons/whatsapp.svg?from-css");
}
```
Query parameter is still exist?


src:
```css
.i-bg-whatsapp-force-inline::before {
  background-image: url("@src/img/icons/whatsapp.svg?from-css&inline");
}
```

output
```css
.i-bg-whatsapp-force-inline::before {
  background-image: url(data:image/svg+xml;base64,...............................;
}
```


src:
```css
.i-bg-whatsapp-force-embed::before {
  background-image: url("@src/img/icons/whatsapp.svg?from-css&dummy&embed");
}
```

output : (only use `module.generator.dataUrl`)
```css
.i-bg-whatsapp-force-embed::before {
  background-image: url("data:image/svg+xml,%3csvg fill='none' version='1.1' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3e %3cpath d='m19.085877 4.8720843c-1.879833-1.8822498-4.379999-2.9193503-7.043888-2.9203053-5.4891664 0-9.9565293 4.4668884-9.9584393 9.957499-9.55e-4 1.755222 0.4579099 3.468444 1.3293232 4.978277l-1.4128832 5.160666 5.2790884-1.384722c1.4544109 0.793611 3.0921889 1.211389 4.7586329 1.211889h0.0043c5.488222 0 9.95611-4.467388 9.957999-9.957999 9.22e-4 -2.6609996-1.0338-5.1625716-2.914133-7.044827zm-2.503944 9.1228597c-0.248778-0.124611-1.472055-0.726277-1.700333-0.809333-0.228222-0.08311-0.393889-0.124611-0.559611 0.124611-0.165667 0.249278-0.642667 0.809834-0.787833 0.9755-0.145167 0.166167-0.290334 0.186722-0.539112 0.06206-0.248722-0.124615-1.050444-0.387226-2.001111-1.234782-0.739611-0.659889-1.2391107-1.474444-1.3842218-1.723722-0.1451667-0.249222-0.0152778-0.383889 0.1088333-0.507555 0.1117222-0.111723 0.2487777-0.290778 0.3733885-0.435945 0.124667-0.145166 0.165722-0.249222 0.248778-0.414944 0.083111-0.1661669 0.041556-0.311278-0.0205-0.4359447-0.062111-0.1246111-0.559611-1.3493887-0.7673332-1.8473887-0.2019999-0.4851166-0.4072777-0.4192221-0.559611-0.4273388-0.1451667-0.00717-0.3108333-0.00859-0.477-0.00859-0.1661666 0-0.4354999 0.062072-0.6637221 0.3113221-0.2282222 0.2492222-0.8709388 0.8513333-0.8709388 2.0756109 0 1.2242782 0.8914943 2.4079992 1.0161054 2.5741662s1.7547221 2.679166 4.2505557 3.757333c0.593555 0.256389 1.057166 0.409666 1.418611 0.524278 0.595944 0.189555 1.138333 0.162833 1.567111 0.09883 0.478-0.07161 1.472111-0.602111 1.679333-1.183222s0.207222-1.079611 0.145166-1.183222c-0.06206-0.103611-0.228222-0.166167-0.476999-0.290778z' clip-rule='evenodd' fill='%2325d366' fill-rule='evenodd'/%3e %3c/svg%3e");
}
```
